### ISSUE TITLE
Does not work with Django 2.0 due to missing on_delete argument in models

### ISSUE THREAD

**Issue by aljp** [rdegges/django-twilio#103]
The django-twilio library does not work with Django 2.0

```
File "/var/app/.venv/lib/python3.6/site-packages/django_twilio/models.py", line 36, in <module>
    class Credential(models.Model):
  File "/var/app/.venv/lib/python3.6/site-packages/django_twilio/models.py", line 56, in Credential
    user = models.OneToOneField(AUTH_USER_MODEL)
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

**Comment by jheld** [comment]
Please check out the latest alpha build on PyPI or build it from master.

**Comment by jheld** [comment]
This has been updated in the 0.9.0 release and is on master. Please re-open if you encounter any issues.
